spring:
  application:
    name: event-bot

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        spring.json.type.mapping: >
          OrderCreatedEvent:com.example.eventbot.domain.event.OrderCreatedEvent,
          OrderCancelledEvent:com.example.eventbot.domain.event.OrderCancelledEvent,
          PaymentConfirmedEvent:com.example.eventbot.domain.event.PaymentConfirmedEvent,
          PaymentCancelledEvent:com.example.eventbot.domain.event.PaymentCancelledEvent